name = "holotable-server"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[durable_objects.bindings]]
name = "MATCH"
class_name = "Match"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Match"]

[[d1_databases]]
binding = "holotable"
database_name = "holotable"
database_id = "11e08a9e-04ac-46b8-8887-47924d203440"
